### ISSUE TITLE
Update all ex-dbs to the latest db-common

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-common#1]
Nemal by sa validovat cely config, pretoze sa lahko mozes stat, ze pridanim novej nody/sekcie sa rozbiju vsetky extractory postavene na `db-extractor-common`.

Riesil som to tu:
https://github.com/keboola/mongodb-extractor/commit/a579643e252f5d37a85ea94e9628f60d424d111a?diff=split#diff-37ee53ec3ef7231300c4768582110476

Predpokladam, ze bude treba zmenit sposob ako sa posiela `data_dir` a `extractor_class`, pripadne ich validovat samostatne, tak ako `parameters`.

**Comment by MiroCillik** [comment]
Vyriesene, validuju sa len `paramters`, `data_dir` a `extractor_class` su presunutu pod sekciu `parameters`.

**Comment by ErikZigo** [comment]
Z hlediska UI(struktura configu) se teda nic vlastne nemeni, jen na backendu?

**Comment by kacurez** [comment]
z hladiska ui by sa mal menit:
- [ ] primaryKey ktory je teraz ako array(predtym bol string) https://github.com/keboola/kbc-ui/issues/517
- [ ] hashovany password, cez #password property https://github.com/keboola/kbc-ui/issues/554

az ked sa vsetky ex-db updatnu na novy ex-db-common tak to budeme moct opravit na ui.

**Comment by kacurez** [comment]
orakel je fixnuty asi tymto commitom:

**Comment by MiroCillik** [comment]
Hotovo
