### ISSUE TITLE
Slice output table larger then 5GB

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-extractor-common#11]
S3 has a 5GB limit on single upload. 
https://goo.gl/lGECDZ
Thus, we need to slice the output table:
https://developers.keboola.com/extend/common-interface/folders/#sliced-tables

Check file size when writing to output table and if needed split it into multiple files.

**Comment by Halama** [comment]
Docker runner now supports multipart upload, so this is no longer issue.
