### ISSUE TITLE
ssh keep alive

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-common#14]
https://keboola.slack.com/archives/C31U6BGJC/p1496739309004800

fixnuto v ssh tunnel repozitari.

## Fixes in each update
- build - environemnt in `.env` file
- build - `docker-compose` version 2
- build - docker - dont override entrypoint https://github.com/keboola/db-extractor-mysql/pull/11/files
- deploy to dev-portal ECR https://github.com/keboola/db-extractor-redshift/commit/93e8e0ffd9421a0dfe024fe7964ceafe50dcf00b

Build cleanup for RS extractor https://github.com/keboola/db-extractor-redshift/pull/2/files

## Updatnout
- [x] ex-db-mysql https://github.com/keboola/db-extractor-mysql/pull/12
- [x] ex-db-pgsql https://github.com/keboola/db-extractor-pgsql/pull/8
- [x] ex-db-redshift https://github.com/keboola/db-extractor-redshift
- [x] ex-db-mssql https://github.com/keboola/db-extractor-mssql
- [x] oracle https://github.com/keboola/db-extractor-oracle
- [ ] impala https://github.com/keboola/db-extractor-impala
- [ ] firebird https://github.com/keboola/db-extractor-firebird
- [x] db2 https://github.com/keboola/db-extractor-db2

**Comment by Halama** [comment]
https://github.com/keboola/ssh-tunnel/issues/1

**Comment by Halama** [comment]
fixnuto v ssh tunelu, stačí ho updatnout v komponentách

**Comment by Halama** [comment]
znovuoteviram pro evidenci updatnutych ex

**Comment by Halama** [comment]
mysql upraveno, nasazeno

**Comment by Halama** [comment]
Upravena docker infra aby podporovala ECR sync akce.

**Comment by Halama** [comment]
Vrácena ECR verze mysql ex s keepalive

**Comment by Halama** [comment]
Redshit switchnut na ECR, ssh tunnel update ještě není mergnutý

**Comment by Halama** [comment]
Nahozen tesing RS https://connection.keboola.com/admin/projects/2703/extractors/keboola.ex-db-redshift/287551509

**Comment by Halama** [comment]
@pivnicek can we divide these extractor menitoned above. I can do these with some problems as you mentioned.
I have `redshift` prepared.

**Comment by Halama** [comment]
Já udělám:
 - mssql
 - firebird
 - impala

**Comment by Halama** [comment]
Redshift hotový

**Comment by pivnicek** [comment]
✅ pgsql

**Comment by Halama** [comment]
@pivnicek will you update that pgsql in dev portal please?

**Comment by Halama** [comment]
@pivnicek also this configuration isn't done https://connection.keboola.com/admin/projects/2703/extractors/keboola.ex-db-pgsql/287599200 even executed

**Comment by Halama** [comment]
mssql komplet hotový

**Comment by pivnicek** [comment]
pgsql devportal updated, sshtest executed

**Comment by Halama** [comment]
it is wrong url i am going to fix it.

**Comment by Halama** [comment]
It is fixed.
Everytime i release the component I do following steps:
- wait until the component is synced to KBC
- execute the component
- check PT if it is used https://papertrailapp.com/events?q=147946154733.dkr.ecr.us-east-1.amazonaws.com%2Fdeveloper-portal-v2%2Fkeboola.ex-db-pgsql%3A1.2.5

**Comment by pivnicek** [comment]
oracle komplet hotovo.

**Comment by Halama** [comment]
Firebird používá jeden projekt a je na starém 3.x common bundle.

**Comment by Halama** [comment]
a Impala nepoužívá nikdo

**Comment by Halama** [comment]
db2:
 - keboola.ex-db-db2-as400
 - https://apps.keboola.com/apps/keboola.ex-db-db2
 - keboola.ex-db-db2-bata

**Comment by Halama** [comment]
`keboola.ex-db-db2-bata` and `keboola.ex-db-db2-as400` has same repository specification.

**Comment by Halama** [comment]
I am going to try to update and integrate firebird extractor

**Comment by Halama** [comment]
firebird i db2 nejede SSH tunnel.
- https://github.com/keboola/db-extractor-db2/issues/5
- https://github.com/keboola/db-extractor-firebird/issues/3

**Comment by Halama** [comment]
Tímpádem to ale nejsou blockery.
Nahodím teď statické IP zpět do produkce a mezitím zkusím updatnout a fixnout firebird.

**Comment by Halama** [comment]
monitoring produkce http://syrup-kibana.internal.keboola.com:5601/?#/discover/DB-extractors?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(columns:!(params.component,startTime,project.name,status,project.id),filters:!(),index:'prod_syrup_*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'params.component:%22keboola.ex-db-mysql%22%20params.component:%22keboola.ex-db-redshift%22%20params.component:%22keboola.ex-db-pgsql%22%20params.component:%22keboola.ex-db-mssql%22%20params.component:%22keboola.ex-db-oracle%22%20params.component:%22keboola.ex-db-db2%22%20params.component:%22keboola.ex-db-firebird%22')),sort:!(createdTime,desc))

**Comment by Halama** [comment]
I've created the orchestration with all these extractors https://connection.keboola.com/admin/projects/2703/orchestrations/288109651/jobs/288110031

**Comment by Halama** [comment]
I've check also error from the days when the fixed IPs were deployed and it looks ok.

**Comment by pivnicek** [comment]
super

**Comment by Halama** [comment]
great job @pivnicek with these extractors! Just one think, please fill the release log when you are releasing tag https://github.com/keboola/db-extractor-redshift/releases thanks
