### ISSUE TITLE
PK support

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-common#2]
ked nastavim PK, dostanem error, ze to ma byt array

**Comment by MiroCillik** [comment]
To ma byt array, lebo ten PK moze byt zlozeny. Robis to cez UI? Alebo cez raw json?

**Comment by kacurez** [comment]
fyi ui to uklada ciste ako string

**Comment by ErikZigo** [comment]
Uz to mam taky nareportovany taky v Zendesku

Je to teda chyba v tom generickym UI? @kacurez fixnes to?

**Comment by ErikZigo** [comment]
Zkusim to fixnout ja. Koukam, ze v KBC UI je uz podobny issue a je prirazeny me:-)

**Comment by kacurez** [comment]
no asi to nefixnes ked to este nepodporuje backend ci?

**Comment by ErikZigo** [comment]
Jaky backend?
https://developers.keboola.com/extend/common-interface/config-file/#output-mapping---basic
Tady v output mappingu to normalne vidim a je tam napsany, ze to ma byt array a ne string

**Comment by kacurez** [comment]
aa som zmylil issue(s sifrovany password) som mimo dnes :)
jasne dalo by sa to fixnut na UI, akurat rozmyslam ci sa tym nic nerozbije pretoze v starom db extractore to bol string, ale asi nic. Neni to ale o uprave out mappingu ale v poli parameters->tables ma query primaryKey a tam to nastavit. Ak sa to fixne tak ako je to navrhovane v https://github.com/keboola/kbc-ui/issues/517 tak tu sa to potom moze zavriet imho.

**Comment by ujovlado** [comment]
@MiroCillik @kacurez @ErikZigo robil som to cez UI, takze asi to bude treba poriesit tam, toto za potom IMHO moze zavret, sorry.

**Comment by ujovlado** [comment]
```php
->scalarNode('primaryKey')
                                ->defaultValue(null)
                            ->end()
```
https://github.com/keboola/db-extractor-common/blob/8e66dc9/src/Keboola/DbExtractor/Configuration/ConfigDefinition.php#L77

**Comment by kacurez** [comment]
aha takze je to treba fixnut aj na backende inac z ui konfig s primaryKey as array neulozi

**Comment by MiroCillik** [comment]
OK, fixnem backend

**Comment by MiroCillik** [comment]
Malo by byt opravene v 3.0.1
