### ISSUE TITLE
Migration to configuration rows

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-common#22]
Depends on: https://github.com/keboola/docker-bundle/issues/150

Instead of listing `tables` (aka queries) in the configuration as an array, we should migrate this so that each table/query is a configuration row.  Connection information will remain in the parent configuration.

**Comment by odinuv** [comment]
config rows is merged and working (https://connection.keboola.com/admin/projects/578/extractors/keboola.ex-db-snowflake/row-test), so this is more of a change in the UI only

**Comment by pivnicek** [comment]
oh wow!  
it may be worth while to clean it up a bit though. 

* remove tables from main configuration
* have each row configuration be a single table (no need for the tables array).

That will help the front end too.

**Comment by pivnicek** [comment]
I'm going to dump "things that need to be changed" here and then organize it  (so this comment will be getting updated for a while).  

The main change introduced by this is that each job will have a single table/query.  There will be a job created for each config row.

### This repo source 
- flatten config definition (no more tables array), the config definition will be flat, and each row will supply it's own table definition.
- similarly, parameter validation and runAction in Application.php will not loop through tables, but just validate the single table.

### This repo tests 
- test configs need to be flattened, 1 test config per table
- adhoc config manipulation in CommonExtractor test will also need to be flattened.

**Comment by Halama** [comment]
I've spent today with db redshift ex and common bundle and it is a bit messy. 
So I would recommend to do cleanup/refactoring before any new features.
I have mentioned few points here https://github.com/keboola/db-extractor-redshift/pull/11

Also it should have dev env similar to https://github.com/keboola/docker-demo-app I was fixing it here for redshift ex https://github.com/keboola/db-extractor-redshift/pull/9 

Also switch to PHP7 and official images would be nice before any other steps.
And check current design of common bundle .

After a clean release of common bundle will be done, it can be tuned on ONE (mysql) extractor as reference.  When it'll settle down other extractors can be upgraded too.
Meanwhile other extractor will be only bugfixed.

**Comment by pivnicek** [comment]
Agreed.  Luckily ex-db-redshift was the weakest by far in the CI, but I will perform an inventory of the others while fixing this retry issue https://github.com/keboola/db-extractor-common/issues/29.  Thank you.

**Comment by pivnicek** [comment]
version 7.0.0 fully supports config rows.
