### ISSUE TITLE
Db Extractors Checkup

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-common#29]
As per https://github.com/keboola/db-extractor-common/issues/22#issuecomment-360489701
For each Db Extractor on the latest version of this library (the big 7), make sure of the following:

- [ ] Docker running php 7.1
- [ ] travis component tests and integration tests in separate run blocks
- [ ] app tests db is isolated and integration test db are separate
- [ ] phpcs
- [ ] phpstan
- [ ] use retry package from vkartaviy/retry
- [ ] test for retry not breaking the CSV 
- [ ] extractor has method level tests
- [ ] extractor has application level tests (exit code tests)
- [ ] extractor has live connection integration tests
- [ ] use `ssh-keys.env` for key vars as per https://github.com/keboola/db-extractor-redshift/pull/11
- [ ] separate docker-compose services for app and dev
- [ ] deprecate phpunit.sh

### Extractor list in order of priority
- [ ] db-extractor-common
- [ ] db-extractor-snowflake
- [ ] db-extractor-mysql
- [ ] db-extractor-pgsql
- [ ] db-extractor-mssql
- [ ] db-extractor-redshift
- [ ] db-extractor-oracle
- [ ] db-extractor-db2

**Comment by pivnicek** [comment]
- [ ] db-extractor-common
- [ ] db-extractor-mysql
- [ ] db-extractor-pgsql
- [ ] db-extractor-mssql
- [ ] db-extractor-snowflake
- [ ] db-extractor-redshift
- [ ] db-extractor-oracle
- [ ] db-extractor-db2

**Comment by pivnicek** [comment]
Checklist for this repo


- [ ] Docker running php 7.1
- [ ] travis component tests and integration tests in separate run blocks
- [ ] app tests db is isolated and integration test db are separate
- [ ] použít Retry knihovnu kterou používáme v docker bundle
- [ ] otestovat pomocí mocku že to při retry nerozbije to CSV - tím pádem trochu zrefaktorovat jeto tam dost divoký ted.

**Comment by Halama** [comment]
there is more, phpcs, phpstan missing, check this please https://github.com/keboola/docker-demo-app

**Comment by pivnicek** [comment]
thanks, updated

**Comment by ErikZigo** [comment]
Neco podobneho jsem driv nacnul https://github.com/keboola/db-writer-common/issues/6

**Comment by pivnicek** [comment]
I don't like the use of constants, APP_NAME and ROOT_PATH.  will refactor that.

**Comment by pivnicek** [comment]
Going to close this with the release of `6.0.0`.  

Each extractor should have it's own checkup issue, no need to track them here.
