### ISSUE TITLE
Support for encrypted password

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-common#3]
Ked mam ulozene zasifrovane heslo, extractor konci s `Param password is missing`

**Comment by MiroCillik** [comment]
To ti robi v tom Mongo extraktore? Nepretazujes metodu `createConnection()`?

**Comment by MiroCillik** [comment]
V config definition je to spravne a potom sa to kontroluje len v testovacom `Common` extraktore.

**Comment by ujovlado** [comment]
@MiroCillik nie, ved tu to bolo zle. Chybala podpora encrypted password. Cize ked som mal v configu len `#password`, tak do `createConnection` sa to nedostalo.

![screenshot_2016-04-28_10-39-36](https://cloud.githubusercontent.com/assets/419849/14880121/8b1aed5e-0d2d-11e6-8623-69a3ae04ac4b.png)

**Comment by ujovlado** [comment]
@MiroCillik to bol error z `createConnection`:
```php
foreach (['host', 'database', 'user', 'password'] as $r) {
    if (!isset($params[$r])) {
        throw new UserException(sprintf("Parameter %s is missing.", $r));
    }
}
```


https://github.com/keboola/db-extractor-common/blob/8e66dc90f9871892696a32eac36fd77d2cca8ca6/src/Keboola/DbExtractor/Extractor/Common.php#L25

**Comment by MiroCillik** [comment]
@ujovlado no ved to myslim, ja ale v svojich child extraktoroch nededim z `Keboola\DbExtractor\Extractor\Common` ale z `Keboola\DbExtractor\Extractor\Extractor`. Ten Common je tu viac menej len kvoli testom. Ale jasne, trebalo to fixnut ;)
