### ISSUE TITLE
Empty row packet -> user error

### ISSUE THREAD

**Issue by odinuv** [keboola/db-extractor-common#37]
I'm pretty sure this used to be handled and retried in some previous versions

\nExporting to in.c-keboola-ex-db-mysql-pics-organizer-25.accounts-test\nEmpty row packet body#0 [internal function]: {closure}(2, 'Empty row packe...', '\/code\/vendor\/ke...', 256, Array)\n#1 \/code\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Extractor\/Extractor.php(256): PDOStatement->fetch(2)\n#2 \/code\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Extractor\/Extractor.php(156): Keboola\\DbExtractor\\Extractor\\Extractor->writeToCsv(Object(PDOStatement), Object(Keboola\\Csv\\CsvFile))\n#3 \/code\/src\/Keboola\/DbExtractor\/Extractor\/MySQL.php(153): Keboola\\DbExtractor\\Extractor\\Extractor->export(Array)\n#4 \/code\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Application.php(153): Keboola\\DbExtractor\\Extractor\\MySQL->export(Array)\n#5 \/code\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#6 \/code\/src\/run.php(66): Keboola\\DbExtractor\\Application->run()\n#7 {main}",

**Comment by pivnicek** [comment]
Yes. thanks for reporting it.

**Comment by odinuv** [comment]
or actually it should retry

**Comment by pivnicek** [comment]
solved in 9.0.0
