### ISSUE TITLE
Better config validation for ConfigRows

### ISSUE THREAD

**Issue by Actimel** [keboola/db-extractor-common#67]
This issue should solve ConfigDefinition consistency better than this work around https://github.com/keboola/db-extractor-common/pull/66.

https://keboola.slack.com/archives/C02CFS0H3/p1536309974000100?thread_ts=1536309437.000100&cid=C02CFS0H3

We want a strict ConfigDefintion for component in case we're running it with action `run`. Against it we also want some other action which doesn't need to be fully configured (basically `parameters.db` node is enough).

Solution might be to have more ConfigDefinitions depends on required action. Basically maybe just 2 of them will be fine: `run` and other actions (e.g. `testConenction` and `getTables`). 

Also we could have defined ConfigDefinition in this repository to avoid duplicated ones in component. In case component will require different ConfigDefinition which is common, we can be able to pass it extra.

**Comment by pivnicek** [comment]
I think we solved this for now.
