### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-extractor-common#7]
Vylepsit/zabudovat retry (backoff) mechanizmus. Teraz je spraveny napr. u PGSQL, treba to odtial vyabstrahovat sem.

**Comment by odinuv** [comment]
+ opravit chybovou hlasku, aby to nepsalo Application Error viz https://keboola.zendesk.com/agent/tickets/5546

`in.c-ex-db-main.delivery_menus_bound_additions\nExporting to in.c-ex-db-main.order_fields\nEmpty row packet body#0 [internal function]: {closure}(2, 'Empty row packe...', '\/home\/vendor\/ke...', 161, Array)\n#1 \/home\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Extractor\/Extractor.php(161): PDOStatement->fetch(2)\n#2 \/home\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Extractor\/Extractor.php(121): Keboola\\DbExtractor\\Extractor\\Extractor->executeQuery('SELECT * FROM `...', Object(Keboola\\Csv\\CsvFile))\n#3 \/home\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Application.php(92): Keboola\\DbExtractor\\Extractor\\Extractor->export(Array)\n#4 \/home\/vendor\/keboola\/db-extractor-common\/src\/Keboola\/DbExtractor\/Application.php(57): Keboola\\DbExtractor\\Application->runAction()\n#5 \/home\/src\/run.php(39): Keboola\\DbExtractor\\Application->run()\n#6 {main}
`

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/db-extractor-common/commit/16c3be5100d71bb1c131764977ea7dda7dff5fe1
