### ISSUE TITLE
notifications seem to be broken?

### ISSUE THREAD

**Issue by odinuv** [keboola/db-extractor-common#74]

**Comment by pivnicek** [comment]
@odinuv not sure what this means, can you elaborate please?

**Comment by odinuv** [comment]
oh yeah, forgot about this one - the build notifications are not going to #build-management ?

**Comment by pivnicek** [comment]
I've got db ex and wr separated to #db-ex-wr-builds

https://keboola.slack.com/archives/C035LGNK5/p1535635942000100
