### ISSUE TITLE
missing argument error as user exception

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-common#80]
Missing argument in constructor ended up as a user exception and it flew under our radar.

http://status.keboola.com/increased-error-rate-in-mysql-extractor

**Comment by pivnicek** [comment]
This
https://github.com/keboola/db-extractor-common/blob/master/src/Keboola/DbExtractor/Extractor/Extractor.php#L193
should only catch PDOExceptions

**Comment by pivnicek** [comment]
This needs to also be the case for the getTables method https://github.com/keboola/db-extractor-mysql/issues/71
