### ISSUE TITLE
Improve UX, list tables, columns, etc

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-extractor-common#9]
Allow user to explore target DB.

**Comment by pivnicek** [comment]
Backend:
- [X] add Get Tables synchronous action
- [X] add metadata writing
- [X] support table and columns in configuration
- [ ] updated extractors

Deployment:
- [ ] verify that all db-extractor composer.json are using proper version declarations
- [ ] deploy db-extractor-common tag 5.0.0
- [ ] mysql
- [ ] pgsql
- [ ] snowflake
- [ ] redshift
- [ ] oracle
- [ ] db2

Frontend:
- [ ] make tabs for simple/advanced
- [ ] simple tab contains table select and column multi-select
- [ ] UI should compose query from `simple` configuration

**Comment by pivnicek** [comment]
Firebird and impala are still on common v^3.0 so won't be on this ride.

**Comment by pivnicek** [comment]
- [ ] provide sample column values

**Comment by pivnicek** [comment]
Frontend:
- [X] convert to jsx
- [ ] table select
- [ ] column selet
- [ ] Compose query from selection
- [ ] exclude Non-implemented components

**Comment by Halama** [comment]
`Compose query from selection` is this required?

**Comment by pivnicek** [comment]
It is right now as the backend requires a query.  The query needs to be composed at some time, I thought to do it in the UI rather than backend.

**Comment by Halama** [comment]
hmm, I doesn' look like a good idea at all. I thought there will be either query or table and columns, but not both.

**Comment by pivnicek** [comment]
My thinking was as follows:

1) The tables/columns need to be converted into a query at some point before any extraction can happen
2) Having the query constructed by selection in the UI also gives a benefit to query writers that they don't need to look-up tables and columns and can add simple filtering.

**Comment by pivnicek** [comment]
I can see there may be an issue with different backends having different identifier quotation requirements

**Comment by Halama** [comment]
I think this should be to completely separated configruation options:
1. Table and columns with metadata fetch 
 ```
{
 "name": "issues",
 "table": "issues",
 "columns": [
   "id",
   "author"
 ]
}
```
2. SQL query
```
{
 "name": "issues",
 "query": "SELECT * FROM issues;"
}
```

**Comment by Halama** [comment]
If you configure this, it should thorw user error that either query or table,columns must be set:
```
{
"name": "issues",
"query": "SELECT * from projects",
"table": "issues",
"columns": [
  "id",
  "author"
]
}
```

**Comment by pivnicek** [comment]
ah, now I see your concern, mismatched selection vs query.
That should definitely throw a user error whichever way it is configured, good point.
But it would be great imo if 
```
 {
"name": "issues",
"query": "SELECT id, author from issues WHERE author_type='customer'",
"table": "issues",
"columns": [
  "id",
  "author"
]
}
```
were allowed.

It obviously requires validating the table and columns with the query though

**Comment by Halama** [comment]
but it will be much more complicated if this will be allowed. It would require query parsing and comparsion.... So I wouln't allowed that. It'll be than imho simplier for the query version to infer somehow the data types from results.

**Comment by pivnicek** [comment]
Yes, I want to avoid query parsing, so my idea was the portion generated by the selection `SELECT id, author from issues`would be invariant and the user could add to it if the liked.

Of course it would maintain the full-query edit ability, but in that case it would not include table and columns in the config

**Comment by pivnicek** [comment]
Final steps and deployment

- [ ] common abstract simple query creator
- [ ] common update configuration validation
- [ ] frontend review https://github.com/keboola/kbc-ui/pull/1097
- [ ] update extractors to hard common version

### create simple query method + tests + new tables/columns live config tests for extractors 
- [ ] 1) mysql
- [ ] 2) mssql
- [ ] 3) pgsql
- [ ] 4) redshift
- [ ] 5) snowflake
- [ ] 6) db2
- [ ] 7) oracle

**Comment by pivnicek** [comment]
Going to close this as the backend is completed.  

Frontend is in https://github.com/keboola/kbc-ui/pull/1097
